name: 'astra'
inputs:
  owner:
    description: 'Name of GitHub organization or owner'
    required: true
  app-id:
    description: 'GitHub App ID'
    required: true
  installation-id:
    description: 'GitHub Installation ID'
    required: true
  pem:
    description: 'GitHub App PEM file'
    required: true
  repo-prefixes:
    description: 'Only repositories containing these prefixes will be processed'
    required: true
  actors:
    description: 'Only pull requests by these actors will be processed'
    required: false
    default: |
      dependabot
  dry-run:
    description: 'Scan repositories but do not rerun workflows or make any changes'
    required: false
    default: 'false'
  debug:
    description: 'Enable debug logging'
    required: false
    default: 'false'
  default-branch:
    description: 'The name of the default branch for your repositories'
    required: false
    default: 'main'
  wait-seconds-between-requests:
    description: 'Slow down requests against the GitHub API to avoid throttling'
    required: false
    default: '2'
  max-run-attempts:
    description: 'A workflow will not be restarted if it has failed this many times'
    required: false
    default: '3'
  expect-required-approving-review-count:
    description: 'Expect branch protection to require at least this number of approving reviews'
    required: false
    default: '1'
  expect-requires-status-checks:
    description: 'Expect branch protection to require status checks'
    required: false
    default: 'true'
  expect-requires-strict-status-checks:
    description: 'Expect branch protection to require branches be up to date before merging'
    required: false
    default: 'true'
  expect-requires-approving-reviews:
    description: 'Expect branch protection to require approving reviews before merging'
    required: false
    default: 'true'
  expect-required-status-checks:
    description: 'Expect branch protection to require at least this number of passing status checks'
    required: false
    default: '1'

runs:
  using: "composite"
  steps:
    - run: go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        INPUT_OWNER: ${{ inputs.owner }}
        INPUT_APP_ID: ${{ inputs.app-id }}
        INPUT_INSTALLATION_ID: ${{ inputs.installation-id }}
        INPUT_PEM: ${{ inputs.pem }}
        INPUT_REPO_PREFIXES: ${{ inputs.repo-prefixes }}
        INPUT_ACTORS: ${{ inputs.actors }}
        INPUT_DRY_RUN: ${{ inputs.dry-run }}
        INPUT_DEBUG: ${{ inputs.debug }}
        INPUT_DEFAULT_BRANCH: ${{ inputs.default-branch }}
        INPUT_WAIT_SECONDS_BETWEEN_REQUESTS: ${{ inputs.wait-seconds-between-requests }}
        INPUT_MAX_RUN_ATTEMPTS: ${{ inputs.max-run-attempts }}
        EXPECT_REQUIRED_APPROVING_REVIEW_COUNT: ${{ inputs.expect-required-approving-review-count }}
        EXPECT_REQUIRES_STATUS_CHECKS: ${{ inputs.expect-requires-status-checks }}
        EXPECT_REQUIRES_STRICT_STATUS_CHECKS: ${{ inputs.expect-requires-strict-status-checks }}
        EXPECT_REQUIRES_APPROVING_REVIEWS: ${{ inputs.expect-requires-approving-reviews }}
        EXPECT_REQUIRED_STATUS_CHECKS: ${{ inputs.expect-required-status-checks }}