name: 'astra'
inputs:
  owner:
    description: 'Name of GitHub organization or owner'
    required: true
  app-id:
    description: 'GitHub App ID'
    required: true
  installation-id:
    description: 'GitHub Installation ID'
    required: true
  pem:
    description: 'GitHub App PEM file'
    required: true
  repo-prefixes:
    description: 'Only repositories containing these prefixes will be processed'
    required: true
  actors:
    description: 'Only pull requests by these actors will be processed'
    required: false
    default: |
      dependabot
  dry-run:
    description: 'Scan repositories but do not rerun workflows or make any changes'
    required: false
    default: 'false'
  debug:
    description: 'Enable debug logging'
    required: false
    default: 'false'
  default-branch:
    description: 'The name of the default branch for your repositories'
    required: false
    default: 'main'
  wait-seconds-between-requests:
    description: 'Slow down requests against the GitHub API to avoid throttling'
    required: false
    default: '2'
  max-run-attempts:
    description: 'A workflow will not be restarted if it has failed this many times'
    required: false
    default: '3'

runs:
  using: "composite"
  steps:
    - run: go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        INPUT_OWNER: ${{ inputs.owner }}
        INPUT_APP_ID: ${{ inputs.app-id }}
        INPUT_INSTALLATION_ID: ${{ inputs.installation-id }}
        INPUT_PEM: ${{ inputs.pem }}
        INPUT_REPO_PREFIXES: ${{ inputs.repo-prefixes }}
        INPUT_ACTORS: ${{ inputs.actors }}
        INPUT_DRY_RUN: ${{ inputs.dry-run }}
        INPUT_DEBUG: ${{ inputs.debug }}
        INPUT_DEFAULT_BRANCH: ${{ inputs.default-branch }}
        INPUT_WAIT_SECONDS_BETWEEN_REQUESTS: ${{ inputs.wait-seconds-between-requests }}
        INPUT_MAX_RUN_ATTEMPTS: ${{ inputs.max-run-attempts }}