on:
  workflow_dispatch:
  push:

jobs:
  gobuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.17

      - name: Go Build
        run: go build -v
